{
 "title": "OpenTelemetry Collector",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "k8s_namespace", "label": "Kubernetes namespace", "query": "oto" },
   { "name": "distro", "query": "adot,otel" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "overall health",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}",
     "legendFormat": "online"
    },
    {
     "expr": "otelcol_process_uptime{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}",
     "legendFormat": "uptime"
    }
   ]
  },
  {
   "title": "[resource usage] CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(otelcol_process_cpu_seconds{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"adot-collector-.*\"}[5m])*100",
     "legendFormat": "Total CPU user and system time in seconds (adot)"
    },
    {
     "expr": "rate(otelcol_process_cpu_seconds{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"otel-collector-.*\"}[5m])*100",
     "legendFormat": "Total CPU user and system time in seconds (otel)"
    }
   ]
  },
  {
   "title": "[resource usage] CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(otelcol_process_cpu_seconds{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}[5m])*100",
     "legendFormat": "Total CPU user and system time in seconds ($distro)"
    }
   ]
  },
  {
   "title": "[resource usage] Memory",
   "type": "timeseries",
   "description": "Memory usage from operating system (OS) and Go runtime",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(otelcol_process_memory_rss{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"adot-collector-.*\"}[5m])",
     "legendFormat": "Total physical memory (adot)"
    },
    {
     "expr": "rate(otelcol_process_memory_rss{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"otel-collector-.*\"}[5m])",
     "legendFormat": "Total physical memory (otel)"
    }
   ]
  },
  {
   "title": "[resource usage] Memory",
   "type": "timeseries",
   "description": "Memory usage from operating system (OS) and Go runtime",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(otelcol_process_runtime_total_alloc_bytes{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}[5m])",
     "legendFormat": "Cumulative bytes allocated for heap objects ($distro)"
    },
    {
     "expr": "rate(otelcol_process_runtime_total_sys_memory_bytes{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}[5m])",
     "legendFormat": "Total bytes of memory obtained from OS ($distro)"
    }
   ]
  },
  {
   "title": "[hostmetrics] CPU",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(system_cpu_time{state=\"user\"}[5m])) + sum(rate(system_cpu_time{state=\"system\"}[5m]))",
     "legendFormat": "overall CPU"
    }
   ]
  },
  {
   "title": "[hostmetrics] Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 5, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "system_memory_usage{state=\"free\"}",
     "legendFormat": "overall CPU (user)"
    }
   ]
  },
  {
   "title": "[hostmetrics] Network",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(rate(system_network_io[5m]))",
     "legendFormat": "overall I/O"
    }
   ]
  },
  {
   "title": "[hostmetrics] Disk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sum(rate(system_disk_io[5m]))", "legendFormat": "overall I/O" }
   ]
  },
  {
   "title": "[hostmetrics] Filesystem",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "system_processes_count{status=\"running\"}"
    }
   ]
  },
  { "title": "Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "scrape stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum without(instance,job,k8s_namespace) (scrape_series_added{k8s_namespace=\"$k8s_namespace\"})",
     "legendFormat": "series added from {{k8s_pod}}"
    }
   ]
  },
  {
   "title": "metrics points received",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(otelcol_receiver_accepted_metric_points{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}[5m])",
     "legendFormat": "{{receiver}}"
    }
   ]
  },
  {
   "title": "metrics points receive failed",
   "type": "timeseries",
   "description": "Number of metric points that could not be pushed into the pipeline\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(otelcol_receiver_refused_metric_points{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}[5m])",
     "legendFormat": "{{receiver}}"
    }
   ]
  },
  { "title": "Processors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "send size performance",
   "type": "timeseries",
   "description": "number of units in batch",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(otelcol_processor_batch_batch_send_size_bucket{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}[5m])) by (le,processor))",
     "legendFormat": "p50 for {{processor}} "
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(otelcol_processor_batch_batch_send_size_bucket{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}[5m])) by (le,processor))",
     "legendFormat": "p90 for {{processor}} "
    }
   ]
  },
  {
   "title": "send size memory performance",
   "type": "timeseries",
   "description": "number of bytes in batch that was sent",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(otelcol_processor_batch_batch_send_size_bytes_bucket{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}[5m])) by (le,processor))",
     "legendFormat": "p50 for {{processor}} "
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(otelcol_processor_batch_batch_send_size_bytes_bucket{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}[5m])) by (le,processor))",
     "legendFormat": "p90 for {{processor}} "
    }
   ]
  },
  { "title": "Exporters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "exporter queue size",
   "type": "timeseries",
   "description": "current size of the retry queue (in batches)\n",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "otelcol_exporter_queue_size{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}"
    }
   ]
  },
  {
   "title": "metrics points sent",
   "type": "timeseries",
   "description": "number of metric points successfully sent to destination\n",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_sent_metric_points{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}[5m])",
     "legendFormat": "{{exporter}}"
    }
   ]
  },
  {
   "title": "metrics points send fails",
   "type": "timeseries",
   "description": "number of metric points failed to be added to the sending queue\n",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(otelcol_exporter_enqueue_failed_metric_points{k8s_namespace=\"$k8s_namespace\",k8s_pod=~\"$distro-collector-.*\"}[5m])",
     "legendFormat": "{{exporter}}"
    }
   ]
  }
 ]
}